module.exports = {
	
	"george": "George Ledin is a professor of computer science at Sonoma State University. This semester, Fall 2016, he is teaching CS three seventy, software design and development, as well as CS three ninety, which is the Computer Science Colloquium.",
    "george ledin": "George Ledin is a professor of computer science at Sonoma State University. This semester, Fall 2016, he is teaching CS three seventy, software design and development, as well as CS three ninety, which is the Computer Science Colloquium.",
	"professor george ledin": "George Ledin is a professor of computer science at Sonoma State University. This semester, Fall 2016, he is teaching CS three seventy, software design and development, as well as CS three ninety, which is the Computer Science Colloquium.",
	"professor ledin": "George Ledin is a professor of computer science at Sonoma State University. This semester, Fall 2016, he is teaching CS three seventy, software design and development, as well as CS three ninety, which is the Computer Science Colloquium.",
	"mr. ledin": "George Ledin is a professor of computer science at Sonoma State University. This semester, Fall 2016, he is teaching CS three seventy, software design and development, as well as CS three ninety, which is the Computer Science Colloquium.",
	"mr. george ledin": "George Ledin is a professor of computer science at Sonoma State University. This semester, Fall 2016, he is teaching CS three seventy, software design and development, as well as CS three ninety, which is the Computer Science Colloquium.",
	
	"tia": "Doctor Teeah Watts is a professor of computer science at Sonoma State University. This semester, Fall 2016, she is teaching CS two ten, Intro to Unix, CS two fifteen, programming 2, and CS four sixty, programming languages.",
	"professor tia watts": "Doctor Teeah Watts is a professor of computer science at Sonoma State University. This semester, Fall 2016, she is teaching CS two ten, Intro to Unix, CS two fifteen, programming 2, and CS four sixty, programming languages.",
	"tia watts": "Doctor Teeah Watts is a professor of computer science at Sonoma State University. This semester, Fall 2016, she is teaching CS two ten, Intro to Unix, CS fifteen, programming 2, and CS four sixty, programming languages.",
	"dr. tia watts": "Doctor Teeah Watts is a professor of computer science at Sonoma State University. This semester, Fall 2016, she is teaching CS two ten, Intro to Unix, CS two fifteen, programming 2, and CS four sixty, programming languages.",
	"dr. watts": "Doctor Teeah Watts is a professor of computer science at Sonoma State University. This semester, Fall 2016, she is teaching CS two ten, Intro to Unix, CS two fifteen, programming 2, and CS four sixty, programming languages.",
	"dr. tia": "Doctor Teeah Watts is a professor of computer science at Sonoma State University. This semester, Fall 2016, she is teaching CS two ten, Intro to Unix, CS two fifteen, programming 2, and CS four sixty, programming languages.",
	"professor watts": "Doctor Teeah Watts is a professor of computer science at Sonoma State University. This semester, Fall 2016, she is teaching CS two ten, Intro to Unix, CS two fifteen, programming 2, and CS four sixty, programming languages.",
	
	"mike": "Mike Lyle is a lecturer of Computer Science at Sonoma State University. This semester, Fall 2016, he is teaching CS two ten, Intro to Unix, as well as CS two fifty two, Intro to Computer Organization.",
	"mike lyle": "Mike Lyle is a lecturer of Computer Science at Sonoma State University. This semester, Fall 2016, he is teaching CS two ten, Intro to Unix, as well as CS two fifty two, Intro to Computer Organization.",
	"professor mike lyle": "Mike Lyle is a lecturer of Computer Science at Sonoma State University. This semester, Fall 2016, he is teaching CS two ten, Intro to Unix, as well as CS two fifty two, Intro to Computer Organization.",
	"professor lyle": "Mike Lyle is a lecturer of Computer Science at Sonoma State University. This semester, Fall 2016, he is teaching CS two ten, Intro to Unix, as well as CS two fifty two, Intro to Computer Organization.",
	
	"ali": "Doctor Alley Kooshesh is a professor and chair of computer science at Sonoma State University. This semester, Fall 2016, he is teaching CS three fifteen, data structures.",
	"ali kooshesh": "Doctor Alley Kooshesh is a professor and chair of computer science at Sonoma State University. This semester, Fall 2016, he is teaching CS three fifteen, data structures.",
	"professor ali kooshesh": "Doctor Alley Kooshesh is a professor and chair of computer science at Sonoma State University. This semester, Fall 2016, he is teaching CS three fifteen, data structures.",
	"professor ali": "Doctor Alley Kooshesh is a professor and chair of computer science at Sonoma State University. This semester, Fall 2016, he is teaching CS three fifteen, data structures.",
	"dr. ali kooshesh": "Doctor Alley Kooshesh is a professor and chair of computer science at Sonoma State University. This semester, Fall 2016, he is teaching CS three fifteen, data structures.",
	"dr. ali": "Doctor Alley Kooshesh is a professor and chair of computer science at Sonoma State University. This semester, Fall 2016, he is teaching CS three fifteen, data structures.",
	"dr. kooshesh": "Doctor Alley Kooshesh is a professor and chair of computer science at Sonoma State University. This semester, Fall 2016, he is teaching CS three fifteen, data structures.",
	"mr. ali kooshesh": "Doctor Alley Kooshesh is a professor and chair of computer science at Sonoma State University. This semester, Fall 2016, he is teaching CS three fifteen, data structures.",
	"mr. kooshesh": "Doctor Alley Kooshesh is a professor and chair of computer science at Sonoma State University. This semester, Fall 2016, he is teaching CS three fifteen, data structures.",
	
	"glenn": "Glenn Carter is a lecturer of Computer Science at Sonoma State University. This semester, Fall 2016, he is teaching cs one oh one, Introduction to Computers and Computing.",
	"glenn carter": "Glenn Carter is a lecturer of Computer Science at Sonoma State University. This semester, Fall 2016, he is teaching cs one oh one, Introduction to Computers and Computing.",
	"professor glenn carter": "Glenn Carter is a lecturer of Computer Science at Sonoma State University. This semester, Fall 2016, he is teaching cs one oh one, Introduction to Computers and Computing.",
	"professor carter": "Glenn Carter is a lecturer of Computer Science at Sonoma State University. This semester, Fall 2016, he is teaching cs one oh one, Introduction to Computers and Computing.",
	"mr. carter": "Glenn Carter is a lecturer of Computer Science at Sonoma State University. This semester, Fall 2016, he is teaching cs one oh one, Introduction to Computers and Computing.",
	"mr. glenn carter": "Glenn Carter is a lecturer of Computer Science at Sonoma State University. This semester, Fall 2016, he is teaching cs one oh one, Introduction to Computers and Computing.",
	
	
	"george's phone number": "George Ledin's office-phone-number is, seven oh seven, six six four, two eight one zero.",
	"george ledin's phone number": "George Ledin's office-phone-number is, seven oh seven, six six four, two eight one zero.",
	"professor george ledin's phone number": "George Ledin's office-phone-number is, seven oh seven, six six four, two eight one zero.",
	"professor ledin's phone number": "George Ledin's office-phone-number is, seven oh seven, six six four, two eight one zero.",
	"george's number": "George Ledin's office-phone-number is, seven oh seven, six six four, two eight one zero.",
	"george ledin's number": "George Ledin's office-phone-number is, seven oh seven, six six four, two eight one zero.",
	"professor george ledin's number": "George Ledin's office-phone-number is, seven oh seven, six six four, two eight one zero.",
	"professor ledin's number": "George Ledin's office-phone-number is, seven oh seven, six six four, two eight one zero.",
	"george's office phone number": "George Ledin's office-phone-number is, seven oh seven, six six four, two eight one zero.",
	"george ledin's office phone number": "George Ledin's office-phone-number is, seven oh seven, six six four, two eight one zero.",
	"professor george ledin's office phone number": "George Ledin's office-phone-number is, seven oh seven, six six four, two eight one zero.",
	"professor ledin's office phone number": "George Ledin's office-phone-number is, seven oh seven, six six four, two eight one zero.",
	"george's office phone number": "George Ledin's office-phone-number is, seven oh seven, six six four, two eight one zero.",
	"george ledin's office phone number": "George Ledin's office-phone-number is, seven oh seven, six six four, two eight one zero.",
	"professor george ledin's office phone number": "George Ledin's office-phone-number is, seven oh seven, six six four, two eight one zero.",
	"professor ledin's office phone number": "George Ledin's office-phone-number is, seven oh seven, six six four, two eight one zero.",
	
	"tia's phone number": "Doctor Teeah Watts's office-phone-number is, seven oh seven, six six four, two eight zero seven.",
	"tia watts's phone number": "Doctor Teeah Watts's office-phone-number is, seven oh seven, six six four, two eight zero seven.",
	"professor tia watts's phone number": "Doctor Teeah Watts's office-phone-number is, seven oh seven, six six four, two eight zero seven.",
	"professor watts's phone number": "Doctor Teeah Watts's office-phone-number is, seven oh seven, six six four, two eight zero seven.",
	"dr. tia watts's phone number": "Doctor Teeah Watts's office-phone-number is, seven oh seven, six six four, two eight zero seven.",
	"dr. tia's phone number": "Doctor Teeah Watts's office-phone-number is, seven oh seven, six six four, two eight zero seven.",
	"dr. watts's phone number": "Doctor Teeah Watts's office-phone-number is, seven oh seven, six six four, two eight zero seven.",
	"tia's number": "Doctor Teeah Watts's office-phone-number is, seven oh seven, six six four, two eight zero seven.",
	"tia watts's number": "Doctor Teeah Watts's office-phone-number is, seven oh seven, six six four, two eight zero seven.",
	"professor tia watts's number": "Doctor Teeah Watts's office-phone-number is, seven oh seven, six six four, two eight zero seven.",
	"professor watts's number": "Doctor Teeah Watts's office-phone-number is, seven oh seven, six six four, two eight zero seven.",
	"dr. tia watts's number": "Doctor Teeah Watts's office-phone-number is, seven oh seven, six six four, two eight zero seven.",
	"dr. tia's phone number": "Doctor Teeah Watts's office-phone-number is, seven oh seven, six six four, two eight zero seven.",
	"dr. watts's phone number": "Doctor Teeah Watts's office-phone-number is, seven oh seven, six six four, two eight zero seven.",
	"tia's office phone number": "Doctor Teeah Watts's office-phone-number is, seven oh seven, six six four, two eight zero seven.",
	"tia watts's office phone number": "Doctor Teeah Watts's office-phone-number is, seven oh seven, six six four, two eight zero seven.",
	"professor tia watts's office phone number": "Doctor Teeah Watts's office-phone-number is, seven oh seven, six six four, two eight zero seven.",
	"professor watts's office phone number": "Doctor Teeah Watts's office-phone-number is, seven oh seven, six six four, two eight zero seven.",
	"dr. tia watts's office phone number": "Doctor Teeah Watts's office-phone-number is, seven oh seven, six six four, two eight zero seven.",
	"dr. tia's office phone number": "Doctor Teeah Watts's office-phone-number is, seven oh seven, six six four, two eight zero seven.",
	"dr. watts's office phone number": "Doctor Teeah Watts's office-phone-number is, seven oh seven, six six four, two eight zero seven.",
	
	"ali's phone number": "Doctor Alley Kooshesh's office-phone-number is, seven oh seven, six six four, two zero eight eight.",
	"ali kooshesh's phone number": "Doctor Alley Kooshesh's office-phone-number is, seven oh seven, six six four, two zero eight eight.",
	"professor ali kooshesh's phone number": "Doctor Alley Kooshesh's office-phone-number is, seven oh seven, six six four, two zero eight eight.",
	"professor kooshesh's phone number": "Doctor Alley Kooshesh's office-phone-number is, seven oh seven, six six four, two zero eight eight.",
	"dr. ali kooshesh's phone number": "Doctor Alley Kooshesh's office-phone-number is, seven oh seven, six six four, two zero eight eight.",
	"dr. ali's phone number": "Doctor Alley Kooshesh's office-phone-number is, seven oh seven, six six four, two zero eight eight.",
	"dr. kooshesh's phone number": "Doctor Alley Kooshesh's office-phone-number is, seven oh seven, six six four, two zero eight eight.",
	"ali's number": "Doctor Alley Kooshesh's office-phone-number is, seven oh seven, six six four, two zero eight eight.",
	"ali kooshesh's number": "Doctor Alley Kooshesh's office-phone-number is, seven oh seven, six six four, two zero eight eight.",
	"professor ali kooshesh's number": "Doctor Alley Kooshesh's office-phone-number is, seven oh seven, six six four, two zero eight eight.",
	"professor kooshesh's number": "Doctor Alley Kooshesh's office-phone-number is, seven oh seven, six six four, two zero eight eight.",
	"dr. ali kooshesh's number": "Doctor Alley Kooshesh's office-phone-number is, seven oh seven, six six four, two zero eight eight.",
	"dr. ali's number": "Doctor Alley Kooshesh's office-phone-number is, seven oh seven, six six four, two zero eight eight.",
	"dr. kooshesh's number": "Doctor Alley Kooshesh's office-phone-number is, seven oh seven, six six four, two zero eight eight.",
	"ali's office phone number": "Doctor Alley Kooshesh's office-phone-number is, seven oh seven, six six four, two zero eight eight.",
	"ali kooshesh's office phone number": "Doctor Alley Kooshesh's office-phone-number is, seven oh seven, six six four, two zero eight eight.",
	"professor ali kooshesh's office phone number": "Doctor Alley Kooshesh's office-phone-number is, seven oh seven, six six four, two zero eight eight.",
	"professor kooshesh's office phone number": "Doctor Alley Kooshesh's office-phone-number is, seven oh seven, six six four, two zero eight eight.",
	"dr. ali kooshesh's office phone number": "Doctor Alley Kooshesh's office-phone-number is, seven oh seven, six six four, two zero eight eight.",
	"dr. ali's phone office phone number": "Doctor Alley Kooshesh's office-phone-number is, seven oh seven, six six four, two zero eight eight.",
	"dr. kooshesh's office phone number": "Doctor Alley Kooshesh's office-phone-number is, seven oh seven, six six four, two zero eight eight.",
	
	"mike's phone number": "Mike Lyle's office-phone-number is, seven oh seven, six six four, two zero eight six.",
	"mike lyle's phone number": "Mike Lyle's office-phone-number is, seven oh seven, six six four, two zero eight six.",
	"professor mike lyle's phone number": "Mike Lyle's office-phone-number is, seven oh seven, six six four, two zero eight six.",
	"professor lyle's phone number": "Mike Lyle's office-phone-number is, seven oh seven, six six four, two zero eight six.",
	"mike's number": "Mike Lyle's office-phone-number is, seven oh seven, six six four, two zero eight six.",
	"mike lyle's number": "Mike Lyle's office-phone-number is, seven oh seven, six six four, two zero eight six.",
	"professor mike lyle's number": "Mike Lyle's office-phone-number is, seven oh seven, six six four, two zero eight six.",
	"professor lyle's number": "Mike Lyle's office-phone-number is, seven oh seven, six six four, two zero eight six.",
	"mike's office phone number": "Mike Lyle's office-phone-number is, seven oh seven, six six four, two zero eight six.",
	"mike lyle's office phone number": "Mike Lyle's office-phone-number is, seven oh seven, six six four, two zero eight six.",
	"professor mike lyle's office phone number": "Mike Lyle's office-phone-number is, seven oh seven, six six four, two zero eight six.",
	"professor lyle's office phone number": "Mike Lyle's office-phone-number is, seven oh seven, six six four, two zero eight six.",
	
	"glenn's phone number": "Glenn Carter's office-phone-number is, seven oh seven, six six four, two nine six one.",
	"glenn carter's phone number": "Glenn Carter's office-phone-number is, seven oh seven, six six four, two nine six one.",
	"professor glenn carter's phone number": "Glenn Carter's office-phone-number is, seven oh seven, six six four, two nine six one.",
	"professor carter's phone number": "Glenn Carter's office-phone-number is, seven oh seven, six six four, two nine six one.",
	"glenn's number": "Glenn Carter's office-phone-number is, seven oh seven, six six four, two nine six one.",
	"glenn carter's number": "Glenn Carter's office-phone-number is, seven oh seven, six six four, two nine six one.",
	"professor glenn carter's number": "Glenn Carter's office-phone-number is, seven oh seven, six six four, two nine six one.",
	"professor carter's number": "Glenn Carter's office-phone-number is, seven oh seven, six six four, two nine six one.",
	"glenn's office phone number": "Glenn Carter's office-phone-number is, seven oh seven, six six four, two nine six one.",
	"glenn carter's office phone number": "Glenn Carter's office-phone-number is, seven oh seven, six six four, two nine six one.",
	"professor glenn carter's office phone number": "Glenn Carter's office-phone-number is, seven oh seven, six six four, two nine six one.",
	"professor carter's office phone number": "Glenn Carter's office-phone-number is, seven oh seven, six six four, two nine six one.",
	
	
	"george's email address": "George Ledin's email address is, george, dot, ledin, @ sonoma dot E-D-U; all lower case.",
	"george ledin's email address": "George Ledin's email address is, george, dot, ledin, @ sonoma E-D-U; all lower case.",
	"professor george ledin's email address": "George Ledin's email address is, george, dot, ledin, @ sonoma dot E-D-U; all lower case.",
	"professor ledin's email address": "George Ledin's email address is, george, dot, ledin, @ sonoma dot E-D-U; all lower case.",
	"george's email": "George Ledin's email address is, george, dot, ledin, @ sonoma dot E-D-U; all lower case.",
	"george ledin's email": "George Ledin's email address is, george, dot, ledin, @ sonoma dot E-D-U; all lower case.",
	"professor george ledin's email": "George Ledin's email address is, george, dot, ledin, @ sonoma dot E-D-U; all lower case.",
	"professor ledin's email": "George Ledin's email address is, george, dot, ledin, @ sonoma dot E-D-U; all lower case.",
	
	"tia's email address": "Doctor Teeah Watts's email address is, teeah, dot, watts, @ sonoma dot E-D-U; all lower case.",
	"tia watts's email address": "Doctor Teeah Watts's email address is, teeah, dot, watts, @ sonoma dot E-D-U; all lower case.",
	"professor tia watts's email address": "Doctor Teeah Watts's email address is, teeah, dot, watts, @ sonoma dot E-D-U; all lower case.",
	"professor watts's email address": "Doctor Teeah Watts's email address is, teeah, dot, watts, @ sonoma dot E-D-U; all lower case.",
	"dr. tia watts's email address": "Doctor Teeah Watts's email address is, teeah, dot, watts, @ sonoma dot E-D-U; all lower case.",
	"dr. tia's email address": "Doctor Teeah Watts's email address is, teeah, dot, watts, @ sonoma dot E-D-U; all lower case.",
	"dr. watts's email address": "Doctor Teeah Watts's email address is, teeah, dot, watts, @ sonoma dot E-D-U; all lower case.",
	"tia's email": "Doctor Teeah Watts's email address is, teeah, dot, watts, @ sonoma dot E-D-U; all lower case.",
	"tia watts's email": "Doctor Teeah Watts's email address is, teeah, dot, watts, @ sonoma dot E-D-U; all lower case.",
	"professor tia watts's email": "Doctor Teeah Watts's email address is, teeah, dot, watts, @ sonoma dot E-D-U; all lower case.",
	"professor watts's email": "Doctor Teeah Watts's email address is, teeah, dot, watts, @ sonoma dot E-D-U; all lower case.",
	"dr. tia watts's email": "Doctor Teeah Watts's email address is, teeah, dot, watts, @ sonoma dot E-D-U; all lower case.",
	"dr. tia's email": "Doctor Teeah Watts's email address is, teeah, dot, watts, @ sonoma dot E-D-U; all lower case.",
	"dr. watts's email": "Doctor Teeah Watts's email address is, teeah, dot, watts, @ sonoma dot E-D-U; all lower case.",
	
	"mike's email address": "Mike Lyle's email address is, lyle, m, @ sonoma dot, E, D, U; all lower case, and all one word.",
	"mike lyle's email address": "Mike Lyle's email address is, lyle, m, @ sonoma dot, E, D, U; all lower case, and all one word.",
	"professor mike lyle's email address": "Mike Lyle's email address is, lyle, m, @ sonoma dot, E, D, U; all lower case, and all one word.",
	"professor lyle's email address": "Mike Lyle's email address is, lyle, m, @ sonoma dot, E, D, U; all lower case, and all one word.",
	"mike's email": "Mike Lyle's email address is, lyle, m, @ sonoma dot, E, D, U; all lower case, and all one word.",
	"mike lyle's email": "Mike Lyle's email address is, lyle, m, @ sonoma dot, E, D, U; all lower case, and all one word.",
	"professor mike lyle's email": "Mike Lyle's email address is, lyle, m, @ sonoma dot, E, D, U; all lower case, and all one word.",
	"professor lyle's email": "Mike Lyle's email address is, lyle, m, @ sonoma dot, E, D, U; all lower case, and all one word.",
	
	"ali's email address": "Doctor Ali Kooshesh's email address is, ali, dot, kooshesh, @ sonoma dot E-D-U; all lower case.",
	"ali kooshesh's email address": "Doctor Ali Kooshesh's email address is, ali, dot, kooshesh, @ sonoma dot E-D-U; all lower case.",
	"professor ali kooshesh's email address": "Doctor Ali Kooshesh's email address is, ali, dot, kooshesh, @ sonoma dot E-D-U; all lower case.",
	"professor ali's email address": "Doctor Ali Kooshesh's email address is, ali, dot, kooshesh, @ sonoma dot E-D-U; all lower case.",
	"dr. ali kooshesh's email address": "Doctor Ali Kooshesh's email address is, ali, dot, kooshesh, @ sonoma dot E-D-U; all lower case.",
	"dr. ali's email address": "Doctor Ali Kooshesh's email address is, ali, dot, kooshesh, @ sonoma dot E-D-U; all lower case.",
	"dr. kooshesh's email address": "Doctor Ali Kooshesh's email address is, ali, dot, kooshesh, @ sonoma dot E-D-U; all lower case.",
	"mr. kooshesh's email address": "Doctor Ali Kooshesh's email address is, ali, dot, kooshesh, @ sonoma dot E-D-U; all lower case.",
	"mr. ali kooshesh's email address": "Doctor Ali Kooshesh's email address is, ali, dot, kooshesh, @ sonoma dot E-D-U; all lower case.",
	"ali's email": "Doctor Ali Kooshesh's email address is, ali, dot, kooshesh, @ sonoma dot E-D-U; all lower case.",
	"ali kooshesh's email": "Doctor Ali Kooshesh's email address is, ali, dot, kooshesh, @ sonoma dot E-D-U; all lower case.",
	"professor ali kooshesh's email": "Doctor Ali Kooshesh's email address is, ali, dot, kooshesh, @ sonoma dot E-D-U; all lower case.",
	"professor ali's email": "Doctor Ali Kooshesh's email address is, ali, dot, kooshesh, @ sonoma dot E-D-U; all lower case.",
	"dr. ali kooshesh's email": "Doctor Ali Kooshesh's email address is, ali, dot, kooshesh, @ sonoma dot E-D-U; all lower case.",
	"dr. ali's email": "Doctor Ali Kooshesh's email address is, ali, dot, kooshesh, @ sonoma dot E-D-U; all lower case.",
	"dr. kooshesh's email": "Doctor Ali Kooshesh's email address is, ali, dot, kooshesh, @ sonoma dot E-D-U; all lower case.",
	"mr. kooshesh's email": "Doctor Ali Kooshesh's email address is, ali, dot, kooshesh, @ sonoma dot E-D-U; all lower case.",
	"mr. ali kooshesh's email": "Doctor Ali Kooshesh's email address is, ali, dot, kooshesh, @ sonoma dot E-D-U; all lower case.",
	
	"glenn's email address": "Glenn Carter's email address is, glenn, dot, carter, @ sonoma dot E-D-U; all lower case.",
	"glenn carter's email address": "Glenn Carter's email address is, glenn, dot, carter, @ sonoma dot E-D-U; all lower case.",
	"professor glenn carter's email address": "Glenn Carter's email address is, glenn, dot, carter, @ sonoma dot E-D-U; all lower case.",
	"professor carter's email address": "Glenn Carter's email address is, glenn, dot, carter, @ sonoma dot E-D-U; all lower case.",
	"glenn's email": "Glenn Carter's email address is, glenn, dot, carter, @ sonoma dot E-D-U; all lower case.",
	"glenn carter's email": "Glenn Carter's email address is, glenn, dot, carter, @ sonoma dot E-D-U; all lower case.",
	"professor glenn carter's email": "Glenn Carter's email address is, glenn, dot, carter, @ sonoma dot E-D-U; all lower case.",
	"professor carter's email": "Glenn Carter's email address is, glenn, dot, carter, @ sonoma dot E-D-U; all lower case.",
	
};
